
services:
  wordpress:
    container_name: wordpress
    image: wordpress:msamhaou
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    build: ./src/wordpress
    volumes:
      - wp:/var/www/wordpress
    restart: always
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    build: ./src/mariadb
    image: mariadb:msamhaou
    restart: always
  nginx:
    ports:
      - "443:443"
    depends_on:
      - wordpress
    container_name: nginx
    volumes:
      - wp:/var/www/wordpress
    build: ./src/nginx
    image: nginx:msamhaou
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      device: "/home/msamhaou/data/"
      type: none
      o: bind